# Generated by Django 4.2.19 on 2025-03-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyRadar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('max_members', models.PositiveIntegerField(default=30)),
                ('join_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='StudyRadar.student')),
                ('members', models.ManyToManyField(blank=True, related_name='study_groups', to='StudyRadar.student')),
            ],
        ),
    ]
